name: Unit tests

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: npm ci

    - name: Unit tests
      run: npm run test
